# Azure Release Pipeline for deploying ARM template and application

resources:
  pipelines:
  - pipeline: build
    source: APCV-405-ClassProjectApp
    trigger: true

variables:
  azureServiceConnection: 'b02e1131-a6a4-4661-b721-3719738aac34'
  azureSubscriptionId: 'a5c15f1e-826b-42a0-a59e-81499cdec096'
  stagingResourceGroup: 'apcv405-staging'
  prodResourceGroup: 'apcv405-prod'
  location: 'eastus2'
  appServiceName: 'apcv405classproject'
  appServiceNameStaging: 'apcv405classproject-staging'
  appServiceNameProd: 'apcv405classproject-prod'

trigger: none

stages:
  - stage: Staging
    displayName: 'Deploy to Staging'
    jobs:
      - job: DeployStagingARM
        displayName: 'Deploy ARM Template to Staging'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            displayName: 'Deploy ARM Template'
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: '$(azureServiceConnection)'
              subscriptionId: '$(azureSubscriptionId)'
              action: 'Create Or Update Resource Group'
              resourceGroupName: '$(stagingResourceGroup)'
              location: '$(location)'
              templateLocation: 'Linked artifact'
              csmFile: 'IaC/arm_template.json'
              deploymentMode: 'Incremental'
              parameters: |
                  location=$(location) appServiceName=$(appServiceNameStaging)
      - job: DeployStagingApp
        displayName: 'Deploy App to Staging'
        dependsOn: DeployStagingARM
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - download: build
            artifact: drop
          - task: AzureWebApp@1
            displayName: 'Deploy to Azure Web App (Staging)'
            inputs:
              azureSubscription: '$(azureServiceConnection)'
              appType: 'webApp'
              appName: '$(appServiceNameStaging)'
              package: '$(Pipeline.Workspace)/drop/**/*.zip'

  - stage: Production
    displayName: 'Deploy to Production'
    dependsOn: Staging
    jobs:
      - job: ManualApproval
        displayName: 'Manual Approval Before Production'
        pool: server
        steps:
          - task: ManualValidation@0
            inputs:
              instructions: 'Approve to deploy to production.'
      - deployment: DeployToProduction
        displayName: 'Deploy to Production Environment'
        environment: 'Production'
        dependsOn: ManualApproval
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureResourceManagerTemplateDeployment@3
                  displayName: 'Deploy ARM Template'
                  inputs:
                    deploymentScope: 'Resource Group'
                    azureResourceManagerConnection: '$(azureServiceConnection)'
                    subscriptionId: '$(azureSubscriptionId)'
                    action: 'Create Or Update Resource Group'
                    resourceGroupName: '$(prodResourceGroup)'
                    location: '$(location)'
                    templateLocation: 'Linked artifact'
                    csmFile: 'IaC/arm_template.json'
                    deploymentMode: 'Incremental'
                    parameters: |
                        location=$(location) appServiceName=$(appServiceNameProd)
                - download: build
                  artifact: drop
                - task: AzureWebApp@1
                  displayName: 'Deploy to Azure Web App (Production)'
                  inputs:
                    azureSubscription: '$(azureServiceConnection)'
                    appType: 'webApp'
                    appName: '$(appServiceNameProd)'
                    package: '$(Pipeline.Workspace)/drop/**/*.zip'

# This pipeline deploys to staging first, then requires manual approval before deploying to production.